package io.reproof.autotrace

import android.app.Activity
import android.content.pm.ApplicationInfo
import android.os.Looper
import android.view.View
import android.widget.TextView
import io.reproof.sdk.ReproRecorder
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.lang.ref.WeakReference
import java.nio.charset.StandardCharsets
import java.util.LinkedHashMap

/**
 * Debug-only, source-vendored hooks inserted around application tap handlers.
 *
 * This file deliberately has no dependency on the target application's classes
 * other than the generated, package-local ReproConfig.  The host copies it and
 * the existing ReproRecorder into the target's debug source set, then emits
 * ReproConfig.kt beside this file.  Every public entry point is best effort:
 * instrumentation problems never change product behaviour.
 */
object ReproAuto {
    private const val RECORD_MODE = "record"
    private const val MAX_ACTIONS = 500
    private const val MAX_DIAGNOSTICS_BYTES = 1024L * 1024L
    private const val MAX_CAPTURE_BYTES = 20L * 1024L * 1024L
    private const val MAX_PROFILE_BYTES = 16 * 1024
    private const val MAX_SITES_BYTES = 64 * 1024
    private const val MAX_CAPTURE_EVENTS = 10_000
    private const val MAX_PATH_LENGTH = 240
    private val IDENTIFIER = Regex("[a-z][a-z0-9_]{0,63}")
    // Site ids are generated by the host as a stable lower-case `s` + hex id.
    private val SITE_ID = Regex("s[0-9a-f]{1,127}")
    private val DECIMAL = Regex("[0-9]{1,9}")
    private val DIGEST = Regex("[0-9a-fA-F]{64}")
    private val lock = Any()
    private var active: Session? = null
    private var nextToken = 1L
    private val observationTokens = LinkedHashMap<Long, Long>()

    /** Call after the activity has rendered its initial content. */
    fun start(activity: Activity) {
        if (!onMainThread()) return
        try {
            if (!isRecordable(activity)) return
            val configuration = RuntimeConfig.load(activity) ?: return
            if (!fixtureMatches(activity, configuration)) return
            // Automatic observation has a looser validity boundary than the
            // replay capture and must continue when its initial state rejects.
            ReproAppLogs.start(
                activity,
                configuration.profileDigest,
                configuration.fixtureId,
                configuration.fixtureVersion,
                configuration.tapTargets,
            )
            var previous: Session? = null
            synchronized(lock) {
                val current = active
                if (current != null && current.activityRef.get() === activity && !current.closed) return
                previous = current
                active = null
                val session = Session(activity, configuration)
                if (!session.initialize()) {
                    session.closeIncomplete()
                    previous?.closeIncomplete()
                    return
                }
                active = session
            }
            previous?.closeIncomplete()
        } catch (_: Throwable) {
            // The application must remain usable when generated configuration or
            // resource lookup is incompatible with the selected profile.
        }
    }

    /** Call from the activity lifecycle when the instrumented activity is gone. */
    fun stop(activity: Activity) {
        if (!onMainThread()) return
        try {
            synchronized(lock) {
                val session = active ?: return
                if (session.activityRef.get() !== activity) return
                active = null
                if (!session.freezeAccepted) session.closeIncomplete()
                else session.closeAfterFreeze()
            }
        } catch (_: Throwable) {
            // Lifecycle cleanup is deliberately non-fatal.
        }
    }

    /**
     * Called immediately before an instrumented tap handler. The automatic app
     * log begins before strict replay validation, so a non-zero token may only
     * represent the app log when replay capture has already become invalid.
     */
    fun beforeTap(activity: Activity, target: String, siteId: String): Long {
        val observationToken = if (onMainThread()) ReproAppLogs.tapBegan(activity, target) else 0L
        if (!onMainThread()) return observationToken
        return try {
            synchronized(lock) {
                val session = activeFor(activity) ?: return observationToken
                if (session.invalid || session.freezeAccepted) return observationToken
                if (session.configuration.sites[siteId] != target) {
                    session.invalidate()
                    return observationToken
                }
                if (session.actions.size >= MAX_ACTIONS) {
                    session.invalidate()
                    return observationToken
                }
                if (!session.flushTextFields(activity)) return observationToken
                val before = session.numericSnapshot(activity) ?: run {
                    session.invalidate()
                    return observationToken
                }
                val previousSequence = session.recorder.lastEventSequence()
                if (!session.recorder.recordTap(target)) {
                    session.invalidate()
                    return observationToken
                }
                val sequence = session.recorder.lastEventSequence()
                if (sequence <= previousSequence || sequence < 1) {
                    session.invalidate()
                    return observationToken
                }
                val token = nextToken++
                if (observationToken != 0L) observationTokens[token] = observationToken
                val action = Action(
                    token = token,
                    eventId = "e$sequence",
                    target = target,
                    siteId = siteId,
                    before = before,
                )
                session.actions += action
                session.pending[token] = action
                token
            }
        } catch (_: Throwable) {
            observationToken
        }
    }

    /** Mark a collected tap as throwing; the instrumented caller rethrows it. */
    fun threw(token: Long) {
        complete(token, "threw")
    }

    /** Mark a collected tap as having returned normally. */
    fun afterTap(token: Long) {
        complete(token, "returned")
    }

    /**
     * Accept an export request from AutoExportReceiver.  The SDK freeze itself
     * and sidecar write are asynchronous; true means the request was accepted.
     */
    fun export(): Boolean {
        if (!onMainThread()) return false
        return try {
            synchronized(lock) {
                val session = active ?: return false
                if (session.invalid || session.freezeAccepted || session.closed) return false
                if (session.pending.isNotEmpty()) {
                    session.invalidate()
                    return false
                }
                val activity = session.activityRef.get()
                if (activity != null && !session.flushTextFields(activity)) return false
                if (session.invalid || session.pending.isNotEmpty()) return false
                val accepted = session.recorder.freezeAndExport { capture ->
                    writeDiagnostics(session, capture)
                }
                if (accepted) session.freezeAccepted = true
                accepted
            }
        } catch (_: Throwable) {
            false
        }
    }

    private fun complete(token: Long, outcome: String) {
        if (token == 0L) return
        val observationToken = synchronized(lock) { observationTokens.remove(token) } ?: token
        if (onMainThread()) {
            if (outcome == "threw") ReproAppLogs.tapThrew(observationToken)
            else ReproAppLogs.tapReturned(observationToken)
        }
        if (!onMainThread()) return
        try {
            synchronized(lock) {
                val session = active ?: return
                if (session.invalid || session.freezeAccepted) return
                val action = session.pending.remove(token) ?: return
                val activity = session.activityRef.get() ?: run {
                    session.invalidate()
                    return
                }
                val after = session.numericSnapshot(activity) ?: run {
                    session.invalidate()
                    return
                }
                action.after = after
                action.outcome = outcome
            }
        } catch (_: Throwable) {
            // Never interfere with the caller's return or exception path.
        }
    }

    private fun activeFor(activity: Activity): Session? {
        val session = active ?: return null
        return if (!session.closed && session.activityRef.get() === activity) session else null
    }

    private fun isRecordable(activity: Activity): Boolean =
        activity.applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE != 0 &&
            activity.intent?.getStringExtra("repro_mode") == RECORD_MODE

    private fun fixtureMatches(activity: Activity, configuration: RuntimeConfig): Boolean =
        activity.intent?.getStringExtra("fixture_id") == configuration.fixtureId &&
            activity.intent?.getIntExtra("fixture_version", Int.MIN_VALUE) == configuration.fixtureVersion

    private fun onMainThread(): Boolean = Looper.myLooper() == Looper.getMainLooper()

    private fun writeDiagnostics(session: Session, capture: File) {
        try {
            val bytes = buildDiagnostics(session, capture) ?: return
            if (bytes.size.toLong() > MAX_DIAGNOSTICS_BYTES) return
            atomicWrite(session.diagnosticsFile, bytes)
        } catch (_: Throwable) {
            // An invalid or incomplete SDK capture simply has no sidecar.
        }
    }

    private fun buildDiagnostics(session: Session, capture: File): ByteArray? {
        if (session.invalid || !capture.isFile || capture.length() > MAX_CAPTURE_BYTES) return null
        val captureJson = JSONObject(capture.readText(StandardCharsets.UTF_8))
        if (captureJson.optBoolean("truncated", true) || captureJson.optBoolean("lostEvents", true)) return null
        val sessionId = captureJson.opt("sessionId") as? String ?: return null
        if (!sessionId.matches(Regex("[A-Za-z0-9_-]{1,128}"))) return null
        val endSequence = captureJson.opt("endSequence") as? Int ?: return null
        if (endSequence < 0) return null
        val events = captureJson.optJSONArray("events") ?: return null
        if (events.length() > MAX_CAPTURE_EVENTS) return null

        val eventById = HashMap<String, JSONObject>()
        var expectedSequence = 1
        for (index in 0 until events.length()) {
            val event = events.optJSONObject(index) ?: return null
            val id = event.opt("id") as? String ?: return null
            val sequence = event.opt("seq") as? Int ?: return null
            val action = event.opt("action") as? String ?: return null
            val target = event.opt("target") as? String ?: return null
            if (id != "e$sequence" || sequence != expectedSequence || !eventById.put(id, event).let { it == null }) {
                return null
            }
            if (action.isEmpty() || target.isEmpty()) return null
            expectedSequence += 1
        }
        if (endSequence != events.length() || expectedSequence != endSequence + 1) return null

        val actions = synchronized(lock) {
            if (session.pending.isNotEmpty() || session.actions.size > MAX_ACTIONS) return@synchronized null
            if (session.actions.isEmpty()) return@synchronized null
            session.actions.map { action ->
                val after = action.after ?: return@synchronized null
                val outcome = action.outcome ?: return@synchronized null
                val event = eventById[action.eventId] ?: return@synchronized null
                if (event.opt("action") != "tap" || event.opt("target") != action.target) {
                    return@synchronized null
                }
                if (!session.configuration.sites.containsKey(action.siteId) ||
                    session.configuration.sites[action.siteId] != action.target ||
                    !validNumericMap(action.before) || !validNumericMap(after) ||
                    outcome !in setOf("returned", "threw")) {
                    return@synchronized null
                }
                JSONObject()
                    .put("eventId", action.eventId)
                    .put("target", action.target)
                    .put("siteId", action.siteId)
                    .put("before", toJson(action.before))
                    .put("after", toJson(after))
                    .put("outcome", outcome)
            }
        } ?: return null

        val actionArray = JSONArray()
        actions.forEach { value -> actionArray.put(value) }
        val result = JSONObject()
            .put("schemaVersion", 1)
            .put("sessionId", sessionId)
            .put("appProfileDigest", session.configuration.profileDigest)
            .put("endSequence", endSequence)
            .put("actions", actionArray)
        return result.toString().toByteArray(StandardCharsets.UTF_8)
    }

    private fun validNumericMap(values: Map<String, String>): Boolean =
        values.size <= 64 && values.keys.all { IDENTIFIER.matches(it) } && values.values.all { DECIMAL.matches(it) }

    private fun toJson(values: Map<String, String>): JSONObject = JSONObject().apply {
        values.forEach { (key, value) -> put(key, value) }
    }

    private fun atomicWrite(destination: File, bytes: ByteArray): Boolean {
        if (bytes.size.toLong() > MAX_DIAGNOSTICS_BYTES) return false
        val parent = destination.parentFile ?: return false
        if (!parent.exists() && !parent.mkdirs() && !parent.isDirectory) return false
        val temporary = File(parent, "${destination.name}.tmp.${System.nanoTime()}")
        return try {
            FileOutputStream(temporary).use { output ->
                output.write(bytes)
                output.flush()
                output.fd.sync()
            }
            if (!temporary.renameTo(destination)) {
                temporary.delete()
                false
            } else true
        } catch (_: Throwable) {
            temporary.delete()
            false
        }
    }

    private data class Action(
        val token: Long,
        val eventId: String,
        val target: String,
        val siteId: String,
        val before: Map<String, String>,
        var after: Map<String, String>? = null,
        var outcome: String? = null,
    )

    private class Session(
        activity: Activity,
        val configuration: RuntimeConfig,
    ) {
        val activityRef = WeakReference(activity)
        val recorder = ReproRecorder(
            context = activity.applicationContext,
            fixtureId = configuration.fixtureId,
            fixtureVersion = configuration.fixtureVersion,
            startState = configuration.startState,
            safeTextTargets = configuration.textTargets,
            tapTargets = configuration.tapTargets,
            scrollTargets = configuration.scrollTargets,
            backTarget = configuration.backTarget,
        )
        val diagnosticsFile = File(activity.filesDir, "repro/diagnostics.json")
        val actions = ArrayList<Action>()
        val pending = LinkedHashMap<Long, Action>()
        private val lastTextValues = LinkedHashMap<String, String>()
        var invalid = false
        var freezeAccepted = false
        var closed = false

        fun initialize(): Boolean {
            if (diagnosticsFile.exists() && !diagnosticsFile.delete()) return false
            val current = activityRef.get() ?: return false
            val nodes = configuration.startNodes
            nodes.forEach { (target, expected) ->
                val actual = readTarget(current, target) ?: return false
                if (actual != expected) return false
                if (target in configuration.textTargets) lastTextValues[target] = actual
            }
            return true
        }

        fun flushTextFields(activity: Activity): Boolean {
            configuration.textTargets.forEach { target ->
                val value = readTarget(activity, target) ?: run {
                    invalidate()
                    return false
                }
                if (value !in SAFE_TEXT_VALUES) {
                    invalidate()
                    return false
                }
                if (lastTextValues[target] != value) {
                    if (!recorder.recordReplace(target, value)) {
                        invalidate()
                        return false
                    }
                    lastTextValues[target] = value
                }
            }
            return true
        }

        fun numericSnapshot(activity: Activity): Map<String, String>? {
            val values = LinkedHashMap<String, String>()
            configuration.numericTargets.forEach { target ->
                val value = readTarget(activity, target) ?: return null
                if (!DECIMAL.matches(value)) return null
                values[target] = value
            }
            return values
        }

        fun invalidate() {
            if (invalid || freezeAccepted) return
            invalid = true
            try {
                recorder.markIncomplete()
            } catch (_: Throwable) {
                // The SDK itself records write failures; product execution remains untouched.
            }
        }

        fun closeIncomplete() {
            if (closed) return
            if (!freezeAccepted) invalidate()
            closed = true
            try {
                recorder.close()
            } catch (_: Throwable) {
                // Cleanup is best effort.
            }
        }

        fun closeAfterFreeze() {
            if (closed) return
            closed = true
            try {
                recorder.close()
            } catch (_: Throwable) {
                // Cleanup is best effort.
            }
        }

        private fun readTarget(activity: Activity, target: String): String? {
            val resourceId = activity.resources.getIdentifier(target, "id", configuration.packageName)
            if (resourceId == 0) return null
            val view = activity.findViewById<View>(resourceId) ?: return null
            return (view as? TextView)?.text?.toString()
        }
    }

    private data class RuntimeConfig(
        val packageName: String,
        val fixtureId: String,
        val fixtureVersion: Int,
        val startState: JSONObject,
        val startNodes: Map<String, String>,
        val tapTargets: Set<String>,
        val textTargets: Set<String>,
        val numericTargets: Set<String>,
        val scrollTargets: Map<String, Set<String>>,
        val backTarget: String,
        val profileDigest: String,
        val sites: Map<String, String>,
    ) {
        companion object {
            fun load(activity: Activity): RuntimeConfig? {
                return try {
                if (ReproConfig.PROFILE_JSON.toByteArray(StandardCharsets.UTF_8).size > MAX_PROFILE_BYTES ||
                    ReproConfig.SITES_JSON.toByteArray(StandardCharsets.UTF_8).size > MAX_SITES_BYTES) return null
                val profile = JSONObject(ReproConfig.PROFILE_JSON)
                val packageName = profile.opt("package") as? String ?: return null
                if (packageName != activity.packageName || !IDENTIFIER_PACKAGE.matches(packageName)) return null
                val fixture = profile.optJSONObject("fixture") ?: return null
                val fixtureId = fixture.opt("id") as? String ?: return null
                val fixtureVersion = fixture.opt("version") as? Int ?: return null
                if (!IDENTIFIER.matches(fixtureId) || fixtureVersion !in 1..1000 || fixture.optJSONObject("inputs")?.length() != 0) return null
                val targetsObject = profile.optJSONObject("targets") ?: return null
                val tap = readIdentifiers(targetsObject.optJSONArray("tap")) ?: return null
                val text = readIdentifiers(targetsObject.optJSONArray("text")) ?: return null
                val numeric = readIdentifiers(targetsObject.optJSONArray("numeric")) ?: return null
                if (numeric.isEmpty() || text.intersect(numeric).isNotEmpty()) return null
                val scroll = readScroll(targetsObject.optJSONObject("scroll")) ?: return null
                val back = targetsObject.opt("back") as? String ?: return null
                if (!IDENTIFIER.matches(back)) return null
                val startState = profile.optJSONObject("startState") ?: return null
                val nodesObject = startState.optJSONObject("nodes") ?: return null
                val nodes = LinkedHashMap<String, String>()
                val nodeKeys = nodesObject.keys()
                while (nodeKeys.hasNext()) {
                    val target = nodeKeys.next()
                    val value = nodesObject.opt(target) as? String ?: return null
                    if (target !in text && target !in numeric) return null
                    if (!IDENTIFIER.matches(target) || (target in text && value !in SAFE_TEXT_VALUES) ||
                        (target in numeric && !DECIMAL.matches(value))) return null
                    nodes[target] = value
                }
                if (nodes.keys != text + numeric) return null
                val digest = ReproConfig.PROFILE_DIGEST
                if (!DIGEST.matches(digest)) return null
                val sites = readSites(JSONArray(ReproConfig.SITES_JSON), tap) ?: return null
                RuntimeConfig(
                    packageName = packageName,
                    fixtureId = fixtureId,
                    fixtureVersion = fixtureVersion,
                    startState = JSONObject(startState.toString()),
                    startNodes = nodes,
                    tapTargets = tap,
                    textTargets = text,
                    numericTargets = numeric,
                    scrollTargets = scroll,
                    backTarget = back,
                    profileDigest = digest,
                    sites = sites,
                )
                } catch (_: Throwable) {
                    null
                }
            }

            private fun readIdentifiers(values: JSONArray?): LinkedHashSet<String>? {
                if (values == null || values.length() > 64) return null
                val result = LinkedHashSet<String>()
                for (index in 0 until values.length()) {
                    val value = values.opt(index) as? String ?: return null
                    if (!IDENTIFIER.matches(value) || !result.add(value)) return null
                }
                return result
            }

            private fun readScroll(values: JSONObject?): Map<String, Set<String>>? {
                if (values == null || values.length() > 16) return null
                val result = LinkedHashMap<String, Set<String>>()
                val keys = values.keys()
                while (keys.hasNext()) {
                    val container = keys.next()
                    if (!IDENTIFIER.matches(container)) return null
                    val ends = readIdentifiers(values.optJSONArray(container)) ?: return null
                    if (ends.isEmpty()) return null
                    result[container] = ends
                }
                return result
            }

            private fun readSites(values: JSONArray, tapTargets: Set<String>): Map<String, String>? {
                if (values.length() == 0 || values.length() > MAX_ACTIONS * 2) return null
                val result = LinkedHashMap<String, String>()
                for (index in 0 until values.length()) {
                    val site = values.optJSONObject(index) ?: return null
                    if (site.keys().asSequence().toSet() != setOf("id", "path", "line", "target", "kind")) return null
                    val id = site.opt("id") as? String ?: return null
                    val path = site.opt("path") as? String ?: return null
                    val line = site.opt("line") as? Int ?: return null
                    val target = site.opt("target") as? String ?: return null
                    val kind = site.opt("kind") as? String ?: return null
                    if (!SITE_ID.matches(id) || !safePath(path) || line < 1 ||
                        kind != "tap" || target !in tapTargets || result.put(id, target) != null) return null
                }
                return if (result.values.toSet() == tapTargets) result else null
            }

            private fun safePath(value: String): Boolean =
                value.length in 1..MAX_PATH_LENGTH && value.split('/').all {
                    it.isNotEmpty() && it.length <= 120 && it.matches(Regex("[A-Za-z0-9_.-]+")) &&
                        it != "." && it != ".."
                }

            private val IDENTIFIER_PACKAGE = Regex("[A-Za-z][A-Za-z0-9_]*(?:\\.[A-Za-z][A-Za-z0-9_]*)+")
        }
    }

    private val SAFE_TEXT_VALUES = setOf("", "QA", "Test")
}
